# Generated by Django 4.2 on 2025-11-25 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mynotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('subject', models.CharField(max_length=50)),
                ('notes_file', models.FileField(upload_to='NotesData')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Reject', 'Reject')], max_length=20)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usersignup')),
            ],
        ),
    ]
